---
version:
  neovim: "v0.8.1"
  graalvm:
    java: 17
    release: 22.3.0
  go:
    version: 1.19.3
nerd_fonts:
  - "FiraMono"
  - "JetBrainsMono"
starship:
  release: "1.12.0"
vivid:
  release: "0.8.0"
zsh:
  plugins:
    zsh_completions:
      release: "0.34.0"
    zsh_autosuggestions:
      release: "v0.7.0"
    zsh_syntax_highlighting:
      release: "0.7.1"
